add 24h total volume
mithraiclabs/bi-dashboard pull request #5
Opened 2021-12-10 23:16 UTC by devexpert127

2021-12-10 23:44 UTC, tomjohn1028 requested changes

2021-12-10 23:44 UTC, tomjohn1028 commented on src/components/OptionMarket/index.tsx
> +        tokensStats(addresses: [
This is getting volume for the spot markets. We want the volume for the active PsyOptions markets. 

To get the `ARRAY_OF_SERUM_MARKET_ADDRESSES` you can do the following:

1. Given all OptionMarkets (as loaded from the TVL task), derive their Seurm market addresses
    * See example from PsyOptions UI [here](https://github.com/mithraiclabs/psyoptions-frontend/blob/staging/src/hooks/useDeriveMultipleSerumMarketAddresses.ts#L17-L23)
2. Group the Serum address as follows
_ETH-CALLS_: any `OptionMarket` where the _underlying_asset_mint_ is the ETH mint
_ETH-PUTS_: any `OptionMarket` where the _quote_asset_mint_ is the ETH mint
_BTC-CALLS_: any `OptionMarket` where the _underlying_asset_mint_ is the BTC mint
_BTC-PUTS_: any `OptionMarket` where the _quote_asset_mint_ is the BTC mint
...and so on grouping other unknown mints that show up in a similar fashion, ignoring USDC
3. For each group above query for the Serum stats with the query below (be mindful of rate limits as this list will grow)

```
{
  dailyStats( markets: ARRAY_OF_SERUM_MARKET_ADDRESSES )
    {
    stats {
      au1h
      vol1hUsd
      au24h
      vol24hUsd
      au7d
      vol7dUsd
    }
  }
}
```

2021-12-13 19:09 UTC, devexpert127 commented
Error: Component must be wrapped with <Container.Provider>
when using useDeriveMultipleSerumMarketAddresses

2021-12-13 19:27 UTC, tomjohn1028 commented
> Error: Component must be wrapped with <Container.Provider>
when using useDeriveMultipleSerumMarketAddresses

You are in a separate codebase so the hook cannot be used out of the box

2021-12-14 17:02 UTC, devexpert127 commented
quoteMint has null in default publickey
const _quoteMint = useRecoilValue(quoteMint);
_quoteMint is null in useDeriveMultipleSerumMarketAddresses
https://github.com/mithraiclabs/bi-dashboard/blob/c3c423802b9e32f4c831760dabf4ca1a8b46c51a/src/hooks/useDeriveMultipleSerumMarketAddresses%20.ts#L15

2021-12-14 22:57 UTC, devexpert127 commented
![image](https://user-images.githubusercontent.com/88482396/146092627-225fe785-098e-4a17-a675-4cf27d897191.png)
This is update version of 24hr and 7d total volumes

2021-12-15 00:36 UTC, tomjohn1028 approved these changes
@devexpert127 Looks great! I only saw the TVL and 7 day volume show up on the UI though, might be missing the 24hr

2021-12-15 05:36 UTC, devexpert127 commented
It has 24hr too, I uploaded only 24hr and 7d now.

2021-12-15 05:37 UTC, devexpert127 commented
![image](https://user-images.githubusercontent.com/88482396/146129552-927b3885-bca3-4f8d-942a-ea606ad1f407.png)

2021-12-15 06:23 UTC, merged

2021-12-17 15:53 UTC, devexpert127 commented
https://github.com/mithraiclabs/bi-dashboard/pull/8

I've updated group by calls and puts